from enum import StrEnum


class MembershipRole(StrEnum):
    OWNER = "OWNER"
    ADMIN = "ADMIN"
    OPERATOR = "OPERATOR"
    VIEWER = "VIEWER"


class PaymentStatus(StrEnum):
    CREATED = "CREATED"
    AUTHORIZED = "AUTHORIZED"
    CAPTURED = "CAPTURED"
    FAILED = "FAILED"
    REFUNDED = "REFUNDED"
    PARTIALLY_REFUNDED = "PARTIALLY_REFUNDED"
    CANCELLED = "CANCELLED"
    UNKNOWN = "UNKNOWN"


class CartStatus(StrEnum):
    ACTIVE = "ACTIVE"
    ABANDONED = "ABANDONED"
    CONVERTED = "CONVERTED"
    EXPIRED = "EXPIRED"


class SubscriptionStatus(StrEnum):
    CREATED = "CREATED"
    ACTIVE = "ACTIVE"
    PENDING = "PENDING"
    HALTED = "HALTED"
    CANCELLED = "CANCELLED"
    COMPLETED = "COMPLETED"


class RecoveryCaseType(StrEnum):
    FAILED_PAYMENT = "FAILED_PAYMENT"
    ABANDONED_CHECKOUT = "ABANDONED_CHECKOUT"
    SUBSCRIPTION_FAILURE = "SUBSCRIPTION_FAILURE"


class RecoveryCaseStatus(StrEnum):
    DETECTED = "DETECTED"
    TRIAGED = "TRIAGED"
    INVESTIGATING = "INVESTIGATING"
    DIAGNOSED = "DIAGNOSED"
    SCORING = "SCORING"
    STRATEGY_SELECTED = "STRATEGY_SELECTED"
    POLICY_CHECK = "POLICY_CHECK"
    AWAITING_APPROVAL = "AWAITING_APPROVAL"
    EXECUTING = "EXECUTING"
    ACTION_COMPLETED = "ACTION_COMPLETED"
    VERIFYING = "VERIFYING"
    RECOVERED = "RECOVERED"
    NOT_RECOVERED = "NOT_RECOVERED"
    RETRY_SCHEDULED = "RETRY_SCHEDULED"
    ESCALATED = "ESCALATED"
    STOPPED = "STOPPED"
    FAILED = "FAILED"


TERMINAL_RECOVERY_STATUSES = frozenset(
    {
        RecoveryCaseStatus.RECOVERED,
        RecoveryCaseStatus.STOPPED,
    }
)


class RecoveryActionType(StrEnum):
    RETRY_NOW = "RETRY_NOW"
    RETRY_LATER = "RETRY_LATER"
    SEND_PAYMENT_LINK = "SEND_PAYMENT_LINK"
    SEND_REMINDER = "SEND_REMINDER"
    OFFER_DISCOUNT = "OFFER_DISCOUNT"
    ESCALATE = "ESCALATE"
    DO_NOTHING = "DO_NOTHING"


class RecoveryActionStatus(StrEnum):
    PENDING = "PENDING"
    PLANNED = "PLANNED"
    APPROVAL_REQUIRED = "APPROVAL_REQUIRED"
    APPROVED = "APPROVED"
    EXECUTING = "EXECUTING"
    SUCCEEDED = "SUCCEEDED"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    BLOCKED = "BLOCKED"
    CANCELLED = "CANCELLED"


class RiskLevel(StrEnum):
    GREEN = "GREEN"
    YELLOW = "YELLOW"
    RED = "RED"


class ApprovalStatus(StrEnum):
    PENDING = "PENDING"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    EXPIRED = "EXPIRED"
    CANCELLED = "CANCELLED"


class WebhookEventStatus(StrEnum):
    RECEIVED = "RECEIVED"
    PROCESSING = "PROCESSING"
    PROCESSED = "PROCESSED"
    FAILED = "FAILED"
    DEAD_LETTER = "DEAD_LETTER"


class IdempotencyKeyStatus(StrEnum):
    IN_PROGRESS = "IN_PROGRESS"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"


class NotificationChannel(StrEnum):
    EMAIL = "EMAIL"
    SMS = "SMS"
    WHATSAPP = "WHATSAPP"
    PUSH = "PUSH"


class NotificationStatus(StrEnum):
    PENDING = "PENDING"
    SENT = "SENT"
    DELIVERED = "DELIVERED"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"


class ActorType(StrEnum):
    SYSTEM = "SYSTEM"
    USER = "USER"
    AGENT = "AGENT"
    WORKER = "WORKER"


class AgentRunStatus(StrEnum):
    RUNNING = "RUNNING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"


class ToolCallStatus(StrEnum):
    PENDING = "PENDING"
    SUCCESS = "SUCCESS"
    FAILED = "FAILED"
    BLOCKED = "BLOCKED"
    APPROVAL_REQUIRED = "APPROVAL_REQUIRED"


class ToolPermission(StrEnum):
    VIEW_RECOVERY = "VIEW_RECOVERY"
    VIEW_CUSTOMER = "VIEW_CUSTOMER"
    VIEW_PAYMENT = "VIEW_PAYMENT"
    RETRY_PAYMENT = "RETRY_PAYMENT"
    CREATE_PAYMENT_LINK = "CREATE_PAYMENT_LINK"
    SEND_NOTIFICATION = "SEND_NOTIFICATION"
    OFFER_DISCOUNT = "OFFER_DISCOUNT"
    ESCALATE = "ESCALATE"
    APPROVE_RECOVERY_ACTION = "APPROVE_RECOVERY_ACTION"
    PAUSE_RECOVERY = "PAUSE_RECOVERY"


DEFAULT_CURRENCY = "INR"
